#!/usr/bin/env bash

path='/Users/Samuel/Desktop'
echo "Files in: $path"
for entry in "$path"/*; do
	echo "Processing: $entry"
        # [ -e "$entry" ] || continue

        name=$(basename "$entry")
	size=$(stat -f%z "$entry")

        if [ -d "$entry" ]; then # get file type
                type="directory"
        else
                type=$(file -b "$entry") #brief description
        fi

        echo "[$type] | Size: $size bytes | Name: $name"
done

echo "completed"
