#!/usr/bin/env bash

greet() ( # parentheses will run in its own subshell
	name=$1
	echo "hello $name"
)

goodbye() {
	name=$1
	echo "bye $name"
}

if ! (return 3>/dev/null); then
	#we are calling this file directly
	greet dave
	goodbye samuel
fi

