#!/usr/bin/env bash

hello() {
	local s=$1
	echo "hello $s!"
}

goodbye() {
	local s=$1
	echo "goodbye $s!"
}

if (($# == 0)); then
	echo 'name required!' >&2
	exit 1
fi


# d* is a wildcard operator, checks if name starts with d
for name in "$@"; do
	case "$name" in 
		d* | a*) hello "$name";;
		b*) hello "$name";;
		*) goodbye "$name";;
	esac
done



