#!/usr/bin/env bash

# show finger command

declare -A shells #associative array
while IFS=: read -r name pass uid gid gecos home shell; do #set IFS for duration of read command
	echo "found user $name"
	# skip comments
	if [[ $name == '#'* ]]; then #test if line starts with #
		continue
	fi

	shells[$name]=$shell
done < /etc/passwd

echo "nobody has the shell: ${shells[nobody]}"
